---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ${releaseName}
  namespace: ${workspaceNamespace}
spec:
  url: "https://itzg.github.io/minecraft-server-charts/"
  interval: 10m
