apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-4.26.3-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    # set ironbank registry credentials
    registryCredentials:
      registry: registry1.dso.mil
      username: username
      password: password

    # set containerd as container runtime in neuvector config
    neuvector:
      values:
        containerd:
          enabled: true

    # disable prometheus operator to not conflict with dkp's
    monitoring:
      values:
        prometheusOperator:
          enabled: false

    # disable kyverno policies, as some of the default installed Kyverno clusterpolicies can cause issues; alternatively, you could use policyexceptions
    kyvernoPolicies:
      enabled: false

    addons:
      metricsServer:
        # -- Toggle deployment of metrics server
        # Acceptable options are enabled: true, enabled: false, enabled: auto
        # true = enabled / false = disabled / auto = automatic (Installs only if metrics API endpoint is not present)
        # We explicitly disable metrics server due to possible race condition where prometheus adapter served metrics apiserivce is not available before installing bigbang
        enabled: false
